parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Elasticsearch\ClientBuilder:
      class: Elasticsearch\ClientBuilder
      factory: [Elasticsearch\ClientBuilder, create]
      calls:
        - method: setHosts
          arguments:
            - ['%env(ELASTICSEARCH_HOSTS_STRING)%']

    Elasticsearch\Client:
      class: Elasticsearch\Client
      factory: ['@Elasticsearch\ClientBuilder', build]

    Shopsys\MicroserviceProductSearch\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    Shopsys\MicroserviceProductSearch\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
